// Real orders from 24-Apr batch. Used when USE_SAMPLE_DATA=true (no Sheets connected).
export const SAMPLE_ORDERS = [
  {
    id: 'ord_1', sn: 1, date: '22 Apr', status: 'Designed',
    name: 'Pooja Tiwari', phone: '9842827680', waNumber: '+977 984-2827680',
    address: 'Bharatpur Chitwan', location: 'outside', branch: 'NARAYANGHAT',
    items: [
      { color: 'Black', size: 'L', print: 'L- virat' },
      { color: 'Black', size: '2XL', print: '2XL- messi' },
    ],
    teeCost: 2598, delivery: 160, prePay: 200, remCod: 2558,
    deliveryType: 'Normal Home Delivery', deadline: '',
  },
  {
    id: 'ord_2', sn: 2, date: '22 Apr', status: 'Designed',
    name: 'anjana', phone: '9700472208', waNumber: 'WA',
    address: 'swoyambhu', location: 'inside', branch: 'KTM',
    items: [{ color: 'White', size: 'L', print: '' }],
    teeCost: 899, delivery: 100, prePay: 500, remCod: 499,
    deliveryType: 'Normal Home Delivery', deadline: 'URGENT, friday',
  },
  {
    id: 'ord_3', sn: 3, date: '23 Apr', status: 'Printed',
    name: 'abisha Magar', phone: '9762578594', waNumber: 'WA',
    address: 'sarlahi hariwon', location: 'outside', branch: 'HARIWON',
    items: [{ color: 'Black', size: 'XL', print: '' }],
    teeCost: 1299, delivery: 170, prePay: 170, remCod: 1299,
    deliveryType: 'Express Branch Delivery', deadline: '',
  },
  {
    id: 'ord_4', sn: 4, date: '23 Apr', status: 'Pressed',
    name: 'Purnima pariyar', phone: '9805866327',
    waNumber: '+974 3003 4547',
    address: 'pokhara prithvi chowk naghdunga',
    location: 'outside', branch: 'POKHARA',
    items: [{ color: 'Black', size: 'XL', print: 'sanu' }],
    teeCost: 999, delivery: 160, prePay: 160, remCod: 999,
    deliveryType: 'Normal Home Delivery', deadline: '',
  },
  {
    id: 'ord_5', sn: 5, date: '23 Apr', status: 'Packed',
    name: 'binisha thapa', phone: '9705787857', waNumber: 'WA',
    address: 'street no 16 lakeside pokhara',
    location: 'outside', branch: 'POKHARA',
    items: [
      { color: 'Black', size: 'L', print: '' },
      { color: 'Black', size: 'L', print: '' },
    ],
    teeCost: 2398, delivery: 160, prePay: 160, remCod: 2398,
    deliveryType: 'Normal Home Delivery', deadline: '',
  },
  {
    id: 'ord_6', sn: 6, date: '23 Apr', status: 'Designed',
    name: 'Dina karki', phone: '9818945022', waNumber: '+977 981-6080611',
    address: 'jhapa bhaundagi', location: 'outside', branch: 'BHADRAPUR',
    items: [{ color: 'Black', size: 'XL', print: 'both side' }],
    teeCost: 1099, delivery: 245, prePay: 100, remCod: 1244,
    deliveryType: 'Express Home Delivery', deadline: '',
  },
  {
    id: 'ord_7', sn: 7, date: '23 Apr', status: 'Designed',
    name: 'Nischal gurung', phone: '9828776561', waNumber: '+977 982-0072316',
    address: 'chakrapath, chundevi mandir & indra maya marg',
    location: 'inside', branch: 'KTM',
    items: [{ color: 'White', size: 'L', print: '' }],
    teeCost: 1199, delivery: 100, prePay: 100, remCod: 1199,
    deliveryType: 'Normal Home Delivery', deadline: 'deliver by sunday',
  },
  {
    id: 'ord_8', sn: 8, date: '24 Apr', status: 'Designed',
    name: '~Alina', phone: '9848926399', waNumber: '+977 984-8926399',
    address: 'Gauri ghat pasupathi', location: 'inside', branch: 'KTM',
    items: [
      { color: 'Dark Green', size: 'S', print: 'husband' },
      { color: 'Dark Green', size: 'XL', print: 'wife' },
    ],
    teeCost: 1998, delivery: 100, prePay: 100, remCod: 1998,
    deliveryType: 'Normal Home Delivery', deadline: '',
  },
];
